// Last updated: 8/3/2026, 12:45:48 PM
import java.util.ArrayList;
import java.util.List;

class Solution {
    public int maxActiveSectionsAfterTrade(String s) {
            int initialOnes = 0;
                    int n = s.length();
                            
                                    for (int i = 0; i < n; i++) {
                                                if (s.charAt(i) == '1') {
                                                                initialOnes++;
                                                                            }
                                                                                    }
                                                                                            
                                                                                                    List<Integer> counts = new ArrayList<>();
                                                                                                            List<Character> chars = new ArrayList<>();
                                                                                                                    
                                                                                                                            int i = 0;
                                                                                                                                    while (i < n) {
                                                                                                                                                char c = s.charAt(i);
                                                                                                                                                            int j = i;
                                                                                                                                                                        while (j < n && s.charAt(j) == c) {
                                                                                                                                                                                        j++;
                                                                                                                                                                                                    }
                                                                                                                                                                                                                counts.add(j - i);
                                                                                                                                                                                                                            chars.add(c);
                                                                                                                                                                                                                                        i = j;
                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                List<Integer> zeros = new ArrayList<>();
                                                                                                                                                                                                                                                                        List<Integer> ones = new ArrayList<>();
                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                        // Extract all '0' block lengths, and only the '1' blocks that are strictly 
                                                                                                                                                                                                                                                                                                // surrounded by '0' blocks (these are our valid trade candidates).
                                                                                                                                                                                                                                                                                                        for (int k = 0; k < chars.size(); k++) {
                                                                                                                                                                                                                                                                                                                    if (chars.get(k) == '0') {
                                                                                                                                                                                                                                                                                                                                    zeros.add(counts.get(k));
                                                                                                                                                                                                                                                                                                                                                    if (k + 1 < chars.size() && chars.get(k + 1) == '1' && 
                                                                                                                                                                                                                                                                                                                                                                        k + 2 < chars.size() && chars.get(k + 2) == '0') {
                                                                                                                                                                                                                                                                                                                                                                                            ones.add(counts.get(k + 1));
                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                // If there are less than two '0' blocks, there is no middle '1' block to convert. 
                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Therefore, a valid trade is impossible.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (zeros.size() < 2) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return initialOnes;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    int k_zeros = zeros.size();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            int[] prefixMaxZero = new int[k_zeros];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    int[] suffixMaxZero = new int[k_zeros];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    prefixMaxZero[0] = zeros.get(0);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for (int k = 1; k < k_zeros; k++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        prefixMaxZero[k] = Math.max(prefixMaxZero[k - 1], zeros.get(k));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                suffixMaxZero[k_zeros - 1] = zeros.get(k_zeros - 1);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        for (int k = k_zeros - 2; k >= 0; k--) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    suffixMaxZero[k] = Math.max(suffixMaxZero[k + 1], zeros.get(k));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            int maxFinalOnes = initialOnes;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Evaluate the optimal trade for every valid middle '1' block
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    for (int j = 0; j < ones.size(); j++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Merging the '1' block to '0' joins it with its adjacent '0' blocks
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            int mergedZero = zeros.get(j) + ones.get(j) + zeros.get(j + 1);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Find the maximum '0' block size available in the rest of the string
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                int otherMaxZero = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (j - 1 >= 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            otherMaxZero = Math.max(otherMaxZero, prefixMaxZero[j - 1]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (j + 2 < k_zeros) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    otherMaxZero = Math.max(otherMaxZero, suffixMaxZero[j + 2]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // We either flip the newly merged block or a strictly larger existing block to '1'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    int bestZeroChoice = Math.max(mergedZero, otherMaxZero);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Calculate candidate ones: Start - lost middle 1s + best gained 1s
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        int cand = initialOnes - ones.get(j) + bestZeroChoice;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    maxFinalOnes = Math.max(maxFinalOnes, cand);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return maxFinalOnes;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }