// Last updated: 8/3/2026, 12:44:30 PM
class Solution {
        public int[] sumAndMultiply(String s, int[][] queries) {
                int n = s.length();
                        long MOD = 1000000007;
                                
                                        long[] P = new long[n + 1];
                                                int[] C = new int[n + 1];
                                                        long[] S = new long[n + 1];
                                                                long[] pow10 = new long[n + 1];
                                                                        
                                                                                pow10[0] = 1;
                                                                                        for (int i = 1; i <= n; i++) {
                                                                                                    pow10[i] = (pow10[i - 1] * 10) % MOD;
                                                                                                            }
                                                                                                                    
                                                                                                                            for (int i = 0; i < n; i++) {
                                                                                                                                        char c = s.charAt(i);
                                                                                                                                                    if (c != '0') {
                                                                                                                                                                    int val = c - '0';
                                                                                                                                                                                    C[i + 1] = C[i] + 1;
                                                                                                                                                                                                    S[i + 1] = S[i] + val;
                                                                                                                                                                                                                    P[i + 1] = (P[i] * 10 + val) % MOD;
                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                C[i + 1] = C[i];
                                                                                                                                                                                                                                                                S[i + 1] = S[i];
                                                                                                                                                                                                                                                                                P[i + 1] = P[i];
                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                    int[] ans = new int[queries.length];
                                                                                                                                                                                                                                                                                                                            for (int i = 0; i < queries.length; i++) {
                                                                                                                                                                                                                                                                                                                                        int l = queries[i][0];
                                                                                                                                                                                                                                                                                                                                                    int r = queries[i][1];
                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                            int len = C[r + 1] - C[l];
                                                                                                                                                                                                                                                                                                                                                                                        long sum = S[r + 1] - S[l];
                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                long x = (P[r + 1] - (P[l] * pow10[len]) % MOD + MOD) % MOD;
                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                        ans[i] = (int) ((x * sum) % MOD);
                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                return ans;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

