// Last updated: 8/3/2026, 12:45:27 PM
import java.util.Arrays;

class Solution {
    public int[] pathExistenceQueries(int n, int[] nums, int maxDiff, int[][] queries) {
            int[] sortedNums = nums.clone();
                    Arrays.sort(sortedNums);
                            
                                    int m = 0;
                                            for (int i = 0; i < n; i++) {
                                                        if (i == 0 || sortedNums[i] != sortedNums[i - 1]) {
                                                                        sortedNums[m++] = sortedNums[i];
                                                                                    }
                                                                                            }
                                                                                                    
                                                                                                            int[][] upR = new int[20][m];
                                                                                                                    int r = 0;
                                                                                                                            for (int l = 0; l < m; l++) {
                                                                                                                                        while (r + 1 < m && sortedNums[r + 1] - sortedNums[l] <= maxDiff) {
                                                                                                                                                        r++;
                                                                                                                                                                    }
                                                                                                                                                                                upR[0][l] = r;
                                                                                                                                                                                        }
                                                                                                                                                                                                
                                                                                                                                                                                                        for (int k = 1; k < 20; k++) {
                                                                                                                                                                                                                    for (int i = 0; i < m; i++) {
                                                                                                                                                                                                                                    upR[k][i] = upR[k - 1][upR[k - 1][i]];
                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                        int[] ans = new int[queries.length];
                                                                                                                                                                                                                                                                                for (int i = 0; i < queries.length; i++) {
                                                                                                                                                                                                                                                                                            int u = queries[i][0];
                                                                                                                                                                                                                                                                                                        int v = queries[i][1];
                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                if (u == v) {
                                                                                                                                                                                                                                                                                                                                                ans[i] = 0;
                                                                                                                                                                                                                                                                                                                                                                continue;
                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                    int val_u = nums[u];
                                                                                                                                                                                                                                                                                                                                                                                                                int val_v = nums[v];
                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                        if (val_u == val_v) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                        ans[i] = 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        continue;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            int id_u = Arrays.binarySearch(sortedNums, 0, m, val_u);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        int id_v = Arrays.binarySearch(sortedNums, 0, m, val_v);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (id_u > id_v) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                int temp = id_u;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                id_u = id_v;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                id_v = temp;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    int curr = id_u;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                int steps = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        for (int k = 19; k >= 0; k--) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (upR[k][curr] < id_v) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            curr = upR[k][curr];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                steps += (1 << k);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (upR[0][curr] < id_v) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ans[i] = -1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ans[i] = steps + 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return ans;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        