// Last updated: 8/3/2026, 12:46:20 PM
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

class Solution {
    int[] lObs;
        int[] rObs;
            int[] maxG;
                int INF = 1_000_000_000;

                    public List<Boolean> getResults(int[][] queries) {
                            int maxX = 0;
                                    for (int[] q : queries) {
                                                maxX = Math.max(maxX, q[1]);
                                                        }
                                                                
                                                                        lObs = new int[4 * (maxX + 1)];
                                                                                rObs = new int[4 * (maxX + 1)];
                                                                                        maxG = new int[4 * (maxX + 1)];
                                                                                                
                                                                                                        Arrays.fill(lObs, INF);
                                                                                                                Arrays.fill(rObs, -1);
                                                                                                                        
                                                                                                                                List<Boolean> res = new ArrayList<>();
                                                                                                                                        
                                                                                                                                                for (int[] q : queries) {
                                                                                                                                                            if (q[0] == 1) {
                                                                                                                                                                            update(1, 0, maxX, q[1]);
                                                                                                                                                                                        } else {
                                                                                                                                                                                                        int x = q[1];
                                                                                                                                                                                                                        int sz = q[2];
                                                                                                                                                                                                                                        int[] qRes = query(1, 0, maxX, 0, x);
                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                        int maxSpace = 0;
                                                                                                                                                                                                                                                                                        if (qRes[0] == INF) {
                                                                                                                                                                                                                                                                                                            maxSpace = x;
                                                                                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                                                                                                maxSpace = Math.max(qRes[2], Math.max(qRes[0], x - qRes[1]));
                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                res.add(maxSpace >= sz);
                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                    return res;
                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                private void update(int node, int l, int r, int idx) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (l == r) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    lObs[node] = idx;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                rObs[node] = idx;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            maxG[node] = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        int mid = l + (r - l) / 2;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (idx <= mid) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            update(2 * node, l, mid, idx);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                update(2 * node + 1, mid + 1, r, idx);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        lObs[node] = Math.min(lObs[2 * node], lObs[2 * node + 1]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                rObs[node] = Math.max(rObs[2 * node], rObs[2 * node + 1]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        maxG[node] = Math.max(maxG[2 * node], maxG[2 * node + 1]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (rObs[2 * node] != -1 && lObs[2 * node + 1] != INF) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    maxG[node] = Math.max(maxG[node], lObs[2 * node + 1] - rObs[2 * node]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        private int[] query(int node, int l, int r, int ql, int qr) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (ql > r || qr < l) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return new int[]{INF, -1, 0};
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (ql <= l && r <= qr) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return new int[]{lObs[node], rObs[node], maxG[node]};
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        int mid = l + (r - l) / 2;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                int[] left = query(2 * node, l, mid, ql, qr);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        int[] right = query(2 * node + 1, mid + 1, r, ql, qr);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        int[] res = new int[3];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                res[0] = Math.min(left[0], right[0]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        res[1] = Math.max(left[1], right[1]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                res[2] = Math.max(left[2], right[2]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (left[1] != -1 && right[0] != INF) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            res[2] = Math.max(res[2], right[0] - left[1]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return res;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        