// Last updated: 8/3/2026, 12:46:03 PM
class Solution {
        public int subsequencePairCount(int[] nums) {
                int MOD = 1000000007;
                        int maxVal = 0;
                                for (int num : nums) {
                                            maxVal = Math.max(maxVal, num);
                                                    }
                                                            
                                                                    long[][] dp = new long[maxVal + 1][maxVal + 1];
                                                                            dp[0][0] = 1;
                                                                                    
                                                                                            for (int x : nums) {
                                                                                                        long[][] nextDp = new long[maxVal + 1][maxVal + 1];
                                                                                                                    for (int g1 = 0; g1 <= maxVal; g1++) {
                                                                                                                                    for (int g2 = 0; g2 <= maxVal; g2++) {
                                                                                                                                                        nextDp[g1][g2] = dp[g1][g2];
                                                                                                                                                                        }
                                                                                                                                                                                    }
                                                                                                                                                                                                
                                                                                                                                                                                                            for (int g1 = 0; g1 <= maxVal; g1++) {
                                                                                                                                                                                                                            for (int g2 = 0; g2 <= maxVal; g2++) {
                                                                                                                                                                                                                                                if (dp[g1][g2] > 0) {
                                                                                                                                                                                                                                                                        int ng1 = g1 == 0 ? x : gcd(g1, x);
                                                                                                                                                                                                                                                                                                nextDp[ng1][g2] = (nextDp[ng1][g2] + dp[g1][g2]) % MOD;
                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                int ng2 = g2 == 0 ? x : gcd(g2, x);
                                                                                                                                                                                                                                                                                                                                                                        nextDp[g1][ng2] = (nextDp[g1][ng2] + dp[g1][g2]) % MOD;
                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                    dp = nextDp;
                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                            long ans = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    for (int g = 1; g <= maxVal; g++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ans = (ans + dp[g][g]) % MOD;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return (int) ans;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    private int gcd(int a, int b) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            while (b != 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        int temp = b;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    b = a % b;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                a = temp;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return a;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
