// Last updated: 8/3/2026, 12:46:09 PM
class Solution {
        public int[] gcdValues(int[] nums, long[] queries) {
                int maxVal = 0;
                        for (int num : nums) {
                                    maxVal = Math.max(maxVal, num);
                                            }
                                                    
                                                            int[] count = new int[maxVal + 1];
                                                                    for (int num : nums) {
                                                                                count[num]++;
                                                                                        }
                                                                                                
                                                                                                        // Array to store the exact number of pairs that have GCD == i
                                                                                                                long[] pairs = new long[maxVal + 1];
                                                                                                                        
                                                                                                                                // Calculate pairs from maxVal down to 1
                                                                                                                                        for (int i = maxVal; i >= 1; i--) {
                                                                                                                                                    long multCount = 0;
                                                                                                                                                                // Count how many numbers are multiples of i
                                                                                                                                                                            for (int j = i; j <= maxVal; j += i) {
                                                                                                                                                                                            multCount += count[j];
                                                                                                                                                                                                        }
                                                                                                                                                                                                                    
                                                                                                                                                                                                                                // Number of pairs where both elements are multiples of i
                                                                                                                                                                                                                                            long currentPairs = multCount * (multCount - 1) / 2;
                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                    // Subtract the pairs that have a GCD strictly greater than i (i.e., multiples of i)
                                                                                                                                                                                                                                                                                for (int j = 2 * i; j <= maxVal; j += i) {
                                                                                                                                                                                                                                                                                                currentPairs -= pairs[j];
                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                    pairs[i] = currentPairs;
                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                            // Prefix sum of pairs to help with binary search
                                                                                                                                                                                                                                                                                                                                                                    long[] prefix = new long[maxVal + 1];
                                                                                                                                                                                                                                                                                                                                                                            for (int i = 1; i <= maxVal; i++) {
                                                                                                                                                                                                                                                                                                                                                                                        prefix[i] = prefix[i - 1] + pairs[i];
                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                // Answer each query using binary search
                                                                                                                                                                                                                                                                                                                                                                                                                        int[] result = new int[queries.length];
                                                                                                                                                                                                                                                                                                                                                                                                                                for (int i = 0; i < queries.length; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                            long target = queries[i];
                                                                                                                                                                                                                                                                                                                                                                                                                                                        int left = 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    int right = maxVal;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                int ans = 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        while (left <= right) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        int mid = left + (right - left) / 2;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (prefix[mid] > target) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ans = mid;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                right = mid - 1; // Try to find a smaller GCD
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    left = mid + 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            result[i] = ans;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return result;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
